apiVersion: v1
kind: Service
metadata:
  name: inventory-management
  namespace: tradeasy
spec:
  type: LoadBalancer
  ports:
    - port: 9003
      targetPort: 9003
  selector:
    app: inventory-management
