apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
  namespace: tradeasy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
        - name: inventory-management
          image: tradeasyacr.azurecr.io/tradeasy-backend-inventory-management:latest
          ports:
            - containerPort: 9003
          env:
            - name: DATABASE_URL
              value: "postgres://tradeasy_postgres:AdminPW01@@tradeasy-db.postgres.database.azure.com:5432/inventory?schema=public"
