apiVersion: v1
kind: Service
metadata:
  name: refund-management
  namespace: tradeasy
spec:
  type: LoadBalancer
  ports:
    - port: 9004
      targetPort: 9004
  selector:
    app: refund-management
