apiVersion: v1
kind: Service
metadata:
  name: product-management
  namespace: tradeasy
spec:
  type: LoadBalancer
  ports:
    - port: 9002
      targetPort: 9002
  selector:
    app: product-management
