apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-management
  namespace: tradeasy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-management
  template:
    metadata:
      labels:
        app: product-management
    spec:
      containers:
        - name: product-management
          image: tradeasyacr.azurecr.io/tradeasy-backend-product-management:latest
          ports:
            - containerPort: 9002
          env:
            - name: DATABASE_URL
              value: "postgres://tradeasy_postgres:AdminPW01@@tradeasy-db.postgres.database.azure.com:5432/product?schema=public"
