apiVersion: v1
kind: Service
metadata:
  name: discount-management
  namespace: tradeasy
spec:
  type: LoadBalancer
  ports:
    - port: 9008
      targetPort: 9008
  selector:
    app: discount-management
