apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management
  namespace: tradeasy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-management
  template:
    metadata:
      labels:
        app: order-management
    spec:
      containers:
        - name: order-management
          image: tradeasyacr.azurecr.io/tradeasy-backend-order-management:latest
          ports:
            - containerPort: 9005
          env:
            - name: DATABASE_URL
              value: "postgres://tradeasy_postgres:AdminPW01@@tradeasy-db.postgres.database.azure.com:5432/order?schema=public"
