apiVersion: v1
kind: Service
metadata:
  name: order-management
  namespace: tradeasy
spec:
  type: LoadBalancer
  ports:
    - port: 9005
      targetPort: 9005
  selector:
    app: order-management
