apiVersion: v1
kind: Service
metadata:
  name: admin-management
  namespace: tradeasy
spec:
  type: LoadBalancer
  ports:
    - port: 9050
      targetPort: 9050
  selector:
    app: admin-management
