apiVersion: apps/v1
kind: Deployment
metadata:
  name: supplier-management
  namespace: tradeasy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supplier-management
  template:
    metadata:
      labels:
        app: supplier-management
    spec:
      containers:
        - name: supplier-management
          image: tradeasyacr.azurecr.io/tradeasy-backend-supplier-management:latest
          ports:
            - containerPort: 9006
          env:
            - name: DATABASE_URL
              value: "postgres://tradeasy_postgres:AdminPW01@@tradeasy-db.postgres.database.azure.com:5432/supplier?schema=public"
