apiVersion: v1
kind: Service
metadata:
  name: supplier-management
  namespace: tradeasy
spec:
  type: LoadBalancer
  ports:
    - port: 9006
      targetPort: 9006
  selector:
    app: supplier-management
