apiVersion: v1
kind: Service
metadata:
  name: mail-sender-service
  namespace: tradeasy
spec:
  type: LoadBalancer
  ports:
    - port: 9011
      targetPort: 9011
  selector:
    app: mail-sender-service
