apiVersion: v1
kind: Service
metadata:
  name: customer-management
  namespace: tradeasy
spec:
  type: LoadBalancer
  ports:
    - port: 9001
      targetPort: 9001
  selector:
    app: customer-management
