name: Deploy to Azure Kubernetes Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: tradeasyacr.azurecr.io
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker-compose build
          docker-compose push

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v2
        with:
          version: 'latest'

      - name: Configure kubectl to connect to AKS
        run: az aks get-credentials --resource-group tradeasy-backend-rg --name tradeasyAKS

      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s-deployment.yaml
